const natural = require('natural')
const classifier = new natural.BayesClassifier()

// Sugars
classifier.addDocument('caster sugar', 'sugar')
classifier.addDocument('dark brown sugar', 'brown sugar')
classifier.addDocument('brown sugar', 'brown sugar')
classifier.addDocument('sugar', 'sugar')
classifier.addDocument('white sugar', 'sugar')
classifier.addDocument('granulated sugar', 'granulated sugar')
classifier.addDocument('golden caster sugar', 'golden caster sugar')
classifier.addDocument('icing sugar', 'icing sugar')
classifier.addDocument('powdered sugar', 'icing sugar')
classifier.addDocument('confectioner sugar', 'icing sugar')
classifier.addDocument('light soft brown sugar', 'light brown sugar')
classifier.addDocument('coconut sugar', 'coconut sugar')
classifier.addDocument('muscovado sugar', 'muscovado sugar')
classifier.addDocument('dark muscovado sugar', 'dark muscovado sugar')
classifier.addDocument('demerara sugar', 'demerara sugar')
classifier.addDocument('pearl sugar', 'pearl sugar')

// Butter
classifier.addDocument('unsalted butter', 'unsalted butter')
classifier.addDocument('salted butter', 'salted butter')
classifier.addDocument('lard', 'lard')

// Flours
classifier.addDocument('self-raising flour', 'self-rising flour')
classifier.addDocument('plain flour', 'plain flour')
classifier.addDocument('all-purpose flour', 'plain flour')
classifier.addDocument('whole wheat flour', 'whole wheat flour')
classifier.addDocument('cornstarch', 'cornflour')
classifier.addDocument('cornflour', 'cornflour')
classifier.addDocument('rice flour', 'rice flour')
classifier.addDocument('rye flour', 'rye flour')
classifier.addDocument('cake flour', 'cake flour')
classifier.addDocument('oat flour', 'oat flour')
classifier.addDocument('bread flour', 'bread flour')
classifier.addDocument('coconut flour', 'coconut flour')
classifier.addDocument('cornmeal', 'polenta')
classifier.addDocument('polenta', 'polenta')

// Fruit
classifier.addDocument('can peaches in juice', 'canned peaches')
classifier.addDocument('fresh peaches', 'peach')
classifier.addDocument('peach slices', 'peach')
classifier.addDocument('peaches', 'peach')
classifier.addDocument('peach juice', 'peach juice')
classifier.addDocument('apple cider vinegar', 'apple cider vinegar')
classifier.addDocument('apple sauce', 'apple sauce')
classifier.addDocument('apple puree', 'apple sauce')
classifier.addDocument('apple juice', 'apple juice')
classifier.addDocument('cooking apples', 'apple')
classifier.addDocument('eating apples', 'apple')
classifier.addDocument('apples', 'apple')
classifier.addDocument('dried apples', 'dried apple')
classifier.addDocument('lemon juice', 'lemon juice')
classifier.addDocument('lemons', 'lemon')
classifier.addDocument('limes', 'lime')
classifier.addDocument('lime juice', 'lime juice')
classifier.addDocument('orange juice', 'orange juice')
classifier.addDocument('oranges', 'orange')
classifier.addDocument('blood orange', 'blood orange')
classifier.addDocument('bananas', 'banana')
classifier.addDocument('dates', 'date')
classifier.addDocument('apricots', 'apricot')
classifier.addDocument('dried apricots', 'dried apricots')
classifier.addDocument('pears', 'pear')
classifier.addDocument('cherries', 'cherries')
classifier.addDocument('maraschino cherries', 'maraschino cherries')
classifier.addDocument('raisins', 'raisins')
classifier.addDocument('figs', 'fig')
classifier.addDocument('mango', 'mango')
classifier.addDocument('pineapple', 'pineapple')
classifier.addDocument('plums', 'plum')
classifier.addDocument('nectarine', 'nectarine')
classifier.addDocument('strawberries', 'strawberries')
classifier.addDocument('blackberries', 'blackberries')
classifier.addDocument('raspberries', 'raspberries')
classifier.addDocument('avocado', 'avocado')

// Eggs
classifier.addDocument('eggs', 'egg')
classifier.addDocument('large eggs', 'egg')
classifier.addDocument('large eggs, at room temperature', 'egg')
classifier.addDocument('boiled eggs', 'egg')
classifier.addDocument('egg yolks', 'egg yolk')
classifier.addDocument('egg whites', 'egg white')

// Spices
classifier.addDocument('kosher salt', 'salt')
classifier.addDocument('salt', 'salt')
classifier.addDocument('sea salt', 'salt')
classifier.addDocument('pinch fine sea salt', 'salt')
classifier.addDocument('pinch salt', 'salt')
classifier.addDocument('pepper', 'black pepper')
classifier.addDocument('paprika', 'paprika')
classifier.addDocument('smoked paprika', 'smoked paprika')
classifier.addDocument('cinnamon', 'ground cinnamon')
classifier.addDocument('ground cinnamon', 'ground cinnamon')
classifier.addDocument('cinnamon stick', 'cinnamon stick')
classifier.addDocument('ginger', 'ground ginger')
classifier.addDocument('ground ginger', 'ground ginger')
classifier.addDocument('ground coriander', 'ground coriander')
classifier.addDocument('ground cloves', 'ground cloves')
classifier.addDocument('cloves', 'ground cloves')
classifier.addDocument('ground cardamom', 'ground cardamom')
classifier.addDocument('cardamom pods', 'cardamom pods')
classifier.addDocument('whole cardamom pods', 'cardamom pods')
classifier.addDocument('cardamom powder', 'ground cardamom')
classifier.addDocument('ground nutmeg', 'ground nutmeg')
classifier.addDocument('ground cumin', 'ground cumin')
classifier.addDocument('ground turmeric', 'ground turmeric')
classifier.addDocument('whole cloves', 'cloves')
classifier.addDocument('chilli powder', 'chilli powder')
classifier.addDocument('chili powder', 'chilli powder')
classifier.addDocument('fennel seeds', 'fennel seeds')
classifier.addDocument('cumin seeds', 'cumin seeds')
classifier.addDocument('garlic powder', 'garlic powder')
classifier.addDocument('onion powder', 'onion powder')
classifier.addDocument('cayenne pepper', 'cayenne pepper')
classifier.addDocument('star anise', 'star anise')
classifier.addDocument('ground allspice', 'ground allspice')
classifier.addDocument('coriander seeds', 'coriander seeds')
classifier.addDocument('curry powder', 'curry powder')
classifier.addDocument('dry oregano', 'dry oregano')
classifier.addDocument('ground white pepper', 'ground white pepper')
classifier.addDocument('five spice', 'Chinese five spice')
classifier.addDocument('curry leaves', 'curry leaves')
classifier.addDocument('mustard seeds', 'mustard seeds')
classifier.addDocument('asafoetida', 'asafoetida')
classifier.addDocument('asafoetida powder', 'asafoetida')
classifier.addDocument('chilli flakes', 'chilli flakes')
classifier.addDocument('chili flakes', 'chilli flakes')
classifier.addDocument('garam masala', 'garam masala')
classifier.addDocument('nigella seeds', 'nigella seeds')
classifier.addDocument('saffron', 'saffron')
classifier.addDocument('mixed spice', 'mixed spice')
classifier.addDocument('ground black pepper', 'ground black pepper')
classifier.addDocument('salt and black pepper', '--')

// Baking
classifier.addDocument('baking powder', 'baking powder')
classifier.addDocument('baking soda', 'bicarbonate of soda')
classifier.addDocument('bicarbonate of soda', 'bicarbonate of soda')
classifier.addDocument('cream of tartar', 'cream of tartar')
classifier.addDocument('vanilla extract', 'vanilla extract')
classifier.addDocument('vanilla essence', 'vanilla essence')
classifier.addDocument('vanilla paste', 'vanilla paste')
classifier.addDocument('vanilla bean paste', 'vanilla paste')
classifier.addDocument('vanilla bean, split', 'vanilla bean')
classifier.addDocument('almond extract', 'almond extract')
classifier.addDocument('orange extract', 'orange extract')
classifier.addDocument('cocoa powder', 'cocoa powder')
classifier.addDocument('cacao powder', 'cacao powder')

classifier.addDocument('single cream', 'single cream')
classifier.addDocument('light cream', 'single cream')
classifier.addDocument('heavy cream', 'double cream')
classifier.addDocument('double cream', 'double cream')
classifier.addDocument('whipping cream', 'whipping cream')
classifier.addDocument('whole milk', 'milk')
classifier.addDocument('full-fat milk', 'milk')
classifier.addDocument('skimmed milk', 'milk')
classifier.addDocument('semi-skimmed milk', 'milk')
classifier.addDocument('milk', 'milk')
classifier.addDocument('evaporated milk', 'evaporated milk')
classifier.addDocument('plant-based milk', 'plant-based milk')
classifier.addDocument('non-dairy milk', 'plant-based milk')
classifier.addDocument('almond milk', 'plant-based milk')
classifier.addDocument('oat milk', 'plant-based milk')
classifier.addDocument('honey', 'honey')
classifier.addDocument('maple syrup', 'maple syrup')
classifier.addDocument('olive oil', 'olive oil')
classifier.addDocument('oil', 'vegetable oil')
classifier.addDocument('ghee', 'ghee')
classifier.addDocument('vegetable oil', 'vegetable oil')
classifier.addDocument('sesame oil', 'sesame oil')
classifier.addDocument('coconut oil', 'coconut oil')
classifier.addDocument('water', 'water')
classifier.addDocument('molasses', 'treacle')
classifier.addDocument('sour cream', 'sour cream')
classifier.addDocument('buttermilk', 'buttermilk')
classifier.addDocument('piece fresh ginger', 'fresh ginger')
classifier.addDocument('fresh ginger', 'fresh ginger')
classifier.addDocument('fresh ginger, chopped', 'fresh ginger')
classifier.addDocument('piece of ginger', 'fresh ginger')
classifier.addDocument('grated ginger', 'fresh ginger')
classifier.addDocument('corn syrup', 'corn syrup')
classifier.addDocument('fish sauce', 'fish sauce')
classifier.addDocument('risotto rice', 'rice')
classifier.addDocument('basmati rice', 'rice')
classifier.addDocument('brown rice', 'brown rice')
classifier.addDocument('rice vinegar', 'rice vinegar')
classifier.addDocument('white vinegar', 'white vinegar')
classifier.addDocument('balsamic vinegar', 'balsamic vinegar')
classifier.addDocument('red wine vinegar', 'red wine vinegar')
classifier.addDocument('garlic cloves', 'garlic')
classifier.addDocument('garlic cloves, sliced', 'garlic')
classifier.addDocument('garlic cloves, finely chopped', 'garlic')
classifier.addDocument('minced garlic', 'garlic')
classifier.addDocument('golden syrup', 'golden syrup')
classifier.addDocument('gelatine leaf', 'gelatine')
classifier.addDocument('Greek yoghurt', 'greek yoghurt')
classifier.addDocument('Greek yogurt', 'greek yoghurt')
classifier.addDocument('plain yogurt', 'yoghurt')
classifier.addDocument('natural yoghurt', 'yoghurt')
classifier.addDocument('plain, not Greek, yogurt', 'yoghurt')
classifier.addDocument('plain yoghurt', 'yoghurt')
classifier.addDocument('espresso', 'coffee')
classifier.addDocument('ground coffee', 'coffee')
classifier.addDocument('tomato paste', 'tomato paste')
classifier.addDocument('cilantro', 'coriander')
classifier.addDocument('chopped fresh coriander', 'coriander')
classifier.addDocument('bay leaves', 'bay leaves')
classifier.addDocument('basil', 'basil')
classifier.addDocument('fresh yeast', 'yeast')
classifier.addDocument('dried yeast', 'yeast')
classifier.addDocument('desiccated coconut', 'desiccated coconut')
classifier.addDocument('sweetened coconut', 'shredded sweetened coconut')
classifier.addDocument('unsweetened coconut', 'shredded unsweetened coconut')
classifier.addDocument('coconut flakes', 'coconut flakes')
classifier.addDocument('rolled oats', 'oats')
classifier.addDocument('soy sauce', 'light soy sauce')
classifier.addDocument('light soy sauce', 'light soy sauce')
classifier.addDocument('dark soy sauce', 'dark soy sauce')
classifier.addDocument('coconut milk', 'coconut milk')
classifier.addDocument('full fat coconut milk', 'coconut milk')
classifier.addDocument('light coconut milk', 'light coconut milk')
classifier.addDocument('coconut cream', 'coconut cream')
classifier.addDocument('treacle', 'treacle')
classifier.addDocument('black treacle', 'black treacle')
classifier.addDocument('protein powder', 'protein powder')
classifier.addDocument('vegetable broth', 'vegetable stock')
classifier.addDocument('vegetable stock', 'vegetable stock')
classifier.addDocument('chicken broth', 'chicken stock')
classifier.addDocument('chicken stock', 'chicken stock')
classifier.addDocument('beef broth', 'beef stock')
classifier.addDocument('beef stock', 'beef stock')
classifier.addDocument('fish broth', 'fish stock')
classifier.addDocument('fish stock', 'fish stock')
classifier.addDocument('flaxseed', 'flaxseed')
classifier.addDocument('green olives', 'olives')
classifier.addDocument('black olives', 'olives')
classifier.addDocument('mustard', 'mustard')
classifier.addDocument('mint', 'mint')
classifier.addDocument('chives', 'chives')
classifier.addDocument('rosemary', 'rosemary')
classifier.addDocument('parsley', 'parsley')
classifier.addDocument('flat-leaf parsley', 'parsley')
classifier.addDocument('chopped flatleaf parsley', 'parsley')
classifier.addDocument('fresh parsley', 'parsley')
classifier.addDocument('dill', 'dill')
classifier.addDocument('thyme sprigs', 'thyme')
classifier.addDocument('lemongrass', 'lemongrass')
classifier.addDocument('rice noodles', 'noodles')
classifier.addDocument('egg noodles', 'noodles')
classifier.addDocument('condensed milk', 'condensed milk')
classifier.addDocument('pumpkin seeds', 'pumpkin seeds')
classifier.addDocument('creme fraiche', 'creme fraiche')
classifier.addDocument('crème fraîche', 'creme fraiche')
classifier.addDocument('small corn tortillas', 'tortillas')
classifier.addDocument('corn tortillas', 'tortillas')
classifier.addDocument('flour tortillas', 'tortillas')
classifier.addDocument('beer', 'beer')
classifier.addDocument('white wine', 'white wine')
classifier.addDocument('red wine', 'red wine')
classifier.addDocument('stem ginger', 'stem ginger')
classifier.addDocument('candied ginger', 'crystallised ginger')
classifier.addDocument('crystallised ginger', 'crystallised ginger')
classifier.addDocument('spaghetti', 'spaghetti')
classifier.addDocument('pasta', 'pasta')
classifier.addDocument('curry paste', 'curry paste')
classifier.addDocument('oyster sauce', 'oyster sauce')
classifier.addDocument('lasagne sheets', 'lasagne sheets')

// Vegetables
classifier.addDocument('carrots', 'carrot')
classifier.addDocument('sweet potatoes', 'sweet potato')
classifier.addDocument('potatoes', 'potato')
classifier.addDocument('diced potatoes', 'potato')
classifier.addDocument('chopped potatoes', 'potato')
classifier.addDocument('red onion', 'red onion')
classifier.addDocument('small onion', 'onion')
classifier.addDocument('small onion, sliced', 'onion')
classifier.addDocument('small onion, chopped', 'onion')
classifier.addDocument('small onion, finely chopped', 'onion')
classifier.addDocument('large onion', 'onion')
classifier.addDocument('large onion, chopped', 'onion')
classifier.addDocument('yellow onion', 'onion')
classifier.addDocument('onion', 'onion')
classifier.addDocument('white onion', 'white onion')
classifier.addDocument('onion', 'white onion')
classifier.addDocument('shallot', 'shallot')
classifier.addDocument('shallot, chopped', 'shallot')
classifier.addDocument('tin pumpkin puree', 'pumpkin puree')
classifier.addDocument('can pumpkin puree', 'pumpkin puree')
classifier.addDocument('pumpkin purée', 'pumpkin puree')
classifier.addDocument('peeled and deseeded pumpkin', 'pumpkin')
classifier.addDocument('bell pepper', 'pepper')
classifier.addDocument('yellow pepper', 'pepper')
classifier.addDocument('green pepper', 'pepper')
classifier.addDocument('orange pepper', 'pepper')
classifier.addDocument('red pepper', 'pepper')
classifier.addDocument('red pepper, chopped', 'pepper')
classifier.addDocument('red peppers, sliced', 'pepper')
classifier.addDocument('pepper chopped', 'pepper')
classifier.addDocument('pepper seeds removed', 'pepper')
classifier.addDocument('butternut squash', 'squash')
classifier.addDocument('can chopped tomatoes', 'can chopped tomatoes')
classifier.addDocument('can chopped tomato', 'can chopped tomatoes')
classifier.addDocument('tomato, diced', 'tomatoes')
classifier.addDocument('tomato, chopped', 'tomatoes')
classifier.addDocument('tomatoes', 'tomatoes')
classifier.addDocument('chillies', 'chilli')
classifier.addDocument('broad beans', 'broad beans')
classifier.addDocument('baby spinach', 'spinach')
classifier.addDocument('spinach', 'spinach')
classifier.addDocument('edemame beans', 'edemame beans')
classifier.addDocument('sugar snap peas', 'sugar snap peas')
classifier.addDocument('snap peas', 'sugar snap peas')
classifier.addDocument('peas', 'peas')
classifier.addDocument('fine green beans', 'green beans')
classifier.addDocument('spring onions', 'spring onions')
classifier.addDocument('scallions', 'spring onions')
classifier.addDocument('cucumber', 'cucumber')
classifier.addDocument('mushrooms', 'mushrooms')
classifier.addDocument('rocket', 'rocket')
classifier.addDocument('arugula', 'rocket')
classifier.addDocument('lettuce', 'lettuce')
classifier.addDocument('aubergine', 'aubergine')
classifier.addDocument('kale', 'kale')
classifier.addDocument('leek', 'leek')
classifier.addDocument('courgette', 'courgette')
classifier.addDocument('zucchini', 'courgette')
classifier.addDocument('tin chickpeas', 'cooked chickpeas')
classifier.addDocument('can chickpeas', 'cooked chickpeas')
classifier.addDocument('rhubarb', 'rhubarb')
classifier.addDocument('brown lentils', 'brown lentils')
classifier.addDocument('red lentils', 'red lentils')
classifier.addDocument('brown lentils', 'brown lentils')
classifier.addDocument('parsnips', 'parsnip')
classifier.addDocument('cauliflower', 'cauliflower')
classifier.addDocument('celery', 'celery')
classifier.addDocument('celery stalk', 'celery')
classifier.addDocument('sweetcorn', 'sweetcorn')
classifier.addDocument('swede', 'swede')
classifier.addDocument('small head cauliflower', 'cauliflower')

// Cheese
classifier.addDocument('mascarpone', 'mascarpone')
classifier.addDocument('mascarpone cheese', 'mascarpone')
classifier.addDocument('cream cheese', 'cream cheese')
classifier.addDocument('parmesan cheese', 'parmesan')
classifier.addDocument('ricotta cheese', 'ricotta')
classifier.addDocument('cheddar', 'cheddar')
classifier.addDocument('burrata', 'burrata')
classifier.addDocument('shredded cheese', 'cheese')
classifier.addDocument('feta cheese', 'feta')
classifier.addDocument('mozzarella', 'mozzarella')

// Nuts
classifier.addDocument('pistachios', 'pistachios')
classifier.addDocument('hazelnuts', 'hazelnuts')
classifier.addDocument('almonds', 'almonds')
classifier.addDocument('blanched almonds', 'blanched almonds')
classifier.addDocument('sliced almonds', 'sliced almonds')
classifier.addDocument('flaked almonds', 'sliced almonds')
classifier.addDocument('pecans', 'pecans')
classifier.addDocument('cashews', 'cashews')
classifier.addDocument('pine nuts', 'pine nuts')
classifier.addDocument('peanuts', 'peanuts')
classifier.addDocument('peanut butter', 'peanut butter')
classifier.addDocument('ground almonds', 'ground almonds')
classifier.addDocument('almond flour', 'ground almonds')
classifier.addDocument('almond meal', 'ground almonds')
classifier.addDocument('almond butter', 'almond butter')
classifier.addDocument('tahini', 'tahini')
classifier.addDocument('walnuts', 'walnuts')

// Chocolate
classifier.addDocument('nutella', 'nutella')
classifier.addDocument('white chocolate chips', 'white chocolate chips')
classifier.addDocument('chocolate chips', 'chocolate chips')
classifier.addDocument('semi-sweet chocolate chips', 'chocolate chips')
classifier.addDocument('dark chocolate', 'dark chocolate')
classifier.addDocument('bittersweet chocolate', 'dark chocolate')
classifier.addDocument('unsweetened chocolate', 'dark chocolate')
classifier.addDocument('milk chocolate', 'milk chocolate')
classifier.addDocument('white chocolate', 'white chocolate')

// Meat
classifier.addDocument('pork shoulder', 'pork shoulder')
classifier.addDocument('pork belly', 'pork belly')
classifier.addDocument('minced pork', 'pork mince')
classifier.addDocument('ground pork', 'pork mince')
classifier.addDocument('gammon', 'gammon')
classifier.addDocument('bacon', 'bacon')
classifier.addDocument('pancetta', 'pancetta')
classifier.addDocument('beef shin', 'beef shin')
classifier.addDocument('chuck roast', 'chuck roast')
classifier.addDocument('skirt steak', 'skirt steak')
classifier.addDocument('ground beef', 'beef mince')
classifier.addDocument('beef mince', 'beef mince')
classifier.addDocument('chicken thighs', 'chicken thigh')
classifier.addDocument('chicken breasts', 'chicken breast')
classifier.addDocument('whole chicken', 'whole chicken')
classifier.addDocument('chicken', 'whole chicken')
classifier.addDocument('cooked chicken', 'cooked chicken')
classifier.addDocument('ground turkey', 'turkey mince')
classifier.addDocument('turkey mince', 'turkey mince')
classifier.addDocument('salmon', 'salmon')
classifier.addDocument('salmon fillet', 'salmon fillet')
classifier.addDocument('prosciutto', 'prosciutto')
classifier.addDocument('tinned tuna', 'tinned tuna')
classifier.addDocument('can tuna', 'tinned tuna')
classifier.addDocument('tuna', 'tuna')
classifier.addDocument('shrimp', 'shrimp')
classifier.addDocument('prawns', 'prawns')
classifier.addDocument('haddock', 'haddock')
classifier.addDocument('smoked haddock', 'smoked haddock')
classifier.addDocument('leg of lamb', 'lamb leg')
classifier.addDocument('shoulder of lamb', 'lamb shoulder')
classifier.addDocument('anchovy fillets', 'anchovy fillets')

classifier.train()
console.log('Classifier trained')

module.exports = classifier
